tab = int(input('Digite um número e veja sua tabuada:'))
print('--------------------------------------')
print('A tabuada de adição do {} : '.format(tab))
print('{} + 1  =  {}'.format(tab,(tab+1)))
print('{} + 2  =  {}'.format(tab,(tab+2)))
print('{} + 3  =  {}'.format(tab,(tab+3)))
print('{} + 4  =  {}'.format(tab,(tab+4)))
print('{} + 5  =  {}'.format(tab,(tab+5)))
print('{} + 6  =  {}'.format(tab,(tab+6)))
print('{} + 7  =  {}'.format(tab,(tab+7)))
print('{} + 8  =  {}'.format(tab,(tab+8)))
print('{} + 9  =  {}'.format(tab,(tab+9)))
print('{} + 10  =  {}'.format(tab,(tab+10)))
print('--------------------------------------')
print('A tabuada de Multiplicação do {} :'.format(tab))
print('{} x 1  =  {}'.format(tab,(tab*1)))
print('{} x 2  =  {}'.format(tab,(tab*2)))
print('{} x 3  =  {}'.format(tab,(tab*3)))
print('{} x 4  =  {}'.format(tab,(tab*4)))
print('{} x 5  =  {}'.format(tab,(tab*5)))
print('{} x 6  =  {}'.format(tab,(tab*6)))
print('{} x 7  =  {}'.format(tab,(tab*7)))
print('{} x 8  =  {}'.format(tab,(tab*8)))
print('{} x 9  =  {}'.format(tab,(tab*9)))
print('{} x 10  =  {}'.format(tab,(tab*10)))
print('--------------------------------------')




