n1 = input('Digite Algum Caractere : ')
print(type(n1))
print(n1 ,': É Numérico ?')
print(n1.isnumeric())
print(n1 ,': É Letra ?')
print(n1.isalpha())
print(n1 ,': É Alfa Numérico ?')
print(n1.isalnum())
print(n1 ,': Tem somente letras maiúsculas ?')
print(n1.isupper())
print(n1 ,': É decimal ?')
print(n1.isdecimal())
print(n1 ,': Esta em Letra Minúscula ? ')
print(n1.islower())
